package dev.carcinogenic.util;

/**
 * @author amy
 * @since 3/31/21.
 */
public final class Meme {
    public static final String MEME = "bee.movie.script.dialogue.transcript.according.to.all.known.laws.of.aviation.the" +
            "re.is.no.way.a.bee.should.be.able.to.fly.its.wings.are.too.small.to.get.its.fat." +
            "little.body.off.the.ground.the.bee.of.course.flies.anyway.because.bees.dont.care" +
            ".what.humans.think.is.impossible.yellow.black.yellow.black.yellow.black.yellow.b" +
            "lack.ooh.black.and.yellow.lets.shake.it.up.a.little.barry.breakfast.is.ready.oom" +
            "ing.hang.on.a.second.hello.barry.adam.oan.you.believe.this.is.happening.i.cant.i" +
            "ll.pick.you.up.looking.sharp.use.the.stairs.your.father.paid.good.money.for.thos" +
            "e.sorry.im.excited.heres.the.graduate.were.very.proud.of.you.son.a.perfect.repor" +
            "t.card.all.bs.very.proud.ma.i.got.a.thing.going.here.you.got.lint.on.your.fuzz.o" +
            "w.thats.me.wave.to.us.well.be.in.row.a118000.bye.barry.i.told.you.stop.flying.in" +
            ".the.house.hey.adam.hey.barry.is.that.fuzz.gel.a.little.special.day.graduation.n" +
            "ever.thought.id.make.it.three.days.grade.school.three.days.high.school.those.wer" +
            "e.awkward.three.days.college.im.glad.i.took.a.day.and.hitchhiked.around.the.hive" +
            ".you.did.come.back.different.hi.barry.artie.growing.a.mustache.looks.good.hear.a" +
            "bout.frankie.yeah.you.going.to.the.funeral.no.im.not.going.everybody.knows.sting" +
            ".someone.you.die.dont.waste.it.on.a.squirrel.such.a.hothead.i.guess.he.could.hav" +
            "e.just.gotten.out.of.the.way.i.love.this.incorporating.an.amusement.park.into.ou" +
            "r.day.thats.why.we.dont.need.vacations.boy.quite.a.bit.of.pomp.under.the.circums" +
            "tances.well.adam.today.we.are.men.we.are.beemen.amen.hallelujah.students.faculty" +
            ".distinguished.bees.please.welcome.dean.buzzwell.welcome.new.hive.oity.graduatin" +
            "g.class.of.a915.that.concludes.our.ceremonies.and.begins.your.career.at.honex.in" +
            "dustries.will.we.pick.ourjob.today.i.heard.its.just.orientation.heads.up.here.we" +
            ".go.keep.your.hands.and.antennas.inside.the.tram.at.all.times.wonder.what.itll.b" +
            "e.like.a.little.scary.welcome.to.honex.a.division.of.honesco.and.a.part.of.the.h" +
            "exagon.group.this.is.it.wow.wow.we.know.that.you.as.a.bee.have.worked.your.whole" +
            ".life.to.get.to.the.point.where.you.can.work.for.your.whole.life.honey.begins.wh" +
            "en.our.valiant.pollen.jocks.bring.the.nectar.to.the.hive.our.topsecret.formula.i" +
            "s.automatically.colorcorrected.scentadjusted.and.bubblecontoured.into.this.sooth" +
            "ing.sweet.syrup.with.its.distinctive.golden.glow.you.know.as.honey.that.girl.was" +
            ".hot.shes.my.cousin.she.is.yes.were.all.cousins.right.youre.right.at.honex.we.co" +
            "nstantly.strive.to.improve.every.aspect.of.bee.existence.these.bees.are.stresste" +
            "sting.a.new.helmet.technology.what.do.you.think.he.makes.not.enough.here.we.have" +
            ".our.latest.advancement.the.krelman.what.does.that.do.oatches.that.little.strand" +
            ".of.honey.that.hangs.after.you.pour.it.saves.us.millions.oan.anyone.work.on.the." +
            "krelman.of.course.most.bee.jobs.are.small.ones.but.bees.know.that.every.small.jo" +
            "b.if.its.done.well.means.a.lot.but.choose.carefully.because.youll.stay.in.the.jo" +
            "b.you.pick.for.the.rest.of.your.life.the.same.job.the.rest.of.your.life.i.didnt." +
            "know.that.whats.the.difference.youll.be.happy.to.know.that.bees.as.a.species.hav" +
            "ent.had.one.day.off.in.27.million.years.so.youll.just.work.us.to.death.well.sure" +
            ".try.wow.that.blew.my.mind.\"whats.the.difference\".how.can.you.say.that.one.job" +
            ".forever.thats.an.insane.choice.to.have.to.make.im.relieved.now.we.only.have.to." +
            "make.one.decision.in.life.but.adam.how.could.they.never.have.told.us.that.why.wo" +
            "uld.you.question.anything.were.bees.were.the.most.perfectly.functioning.society." +
            "on.earth.you.ever.think.maybe.things.work.a.little.too.well.here.like.what.give." +
            "me.one.example.i.dont.know.but.you.know.what.im.talking.about.please.clear.the.g" +
            "ate.royal.nectar.force.on.approach.wait.a.second.oheck.it.out.hey.those.are.poll" +
            "en.jocks.wow.ive.never.seen.them.this.close.they.know.what.its.like.outside.the." +
            "hive.yeah.but.some.dont.come.back.hey.jocks.hi.jocks.you.guys.did.great.youre.mo" +
            "nsters.youre.sky.freaks.i.love.it.i.love.it.i.wonder.where.they.were.i.dont.know" +
            ".their.days.not.planned.outside.the.hive.flying.who.knows.where.doing.who.knows." +
            "what.you.cantjust.decide.to.be.a.pollen.jock.you.have.to.be.bred.for.that.right." +
            "look.thats.more.pollen.than.you.and.i.will.see.in.a.lifetime.its.just.a.status.s" +
            "ymbol.bees.make.too.much.of.it.perhaps.unless.youre.wearing.it.and.the.ladies.se" +
            "e.you.wearing.it.those.ladies.arent.they.our.cousins.too.distant.distant.look.at" +
            ".these.two.oouple.of.hive.harrys.lets.have.fun.with.them.it.must.be.dangerous.be" +
            "ing.a.pollen.jock.yeah.once.a.bear.pinned.me.against.a.mushroom.he.had.a.paw.on." +
            "my.throat.and.with.the.other.he.was.slapping.me.oh.my.i.never.thought.id.knock.h" +
            "im.out.what.were.you.doing.during.this.trying.to.alert.the.authorities.i.can.aut" +
            "ograph.that.a.little.gusty.out.there.today.wasnt.it.comrades.yeah.gusty.were.hit" +
            "ting.a.sunflower.patch.six.miles.from.here.tomorrow.six.miles.huh.barry.a.puddle" +
            ".jump.for.us.but.maybe.youre.not.up.for.it.maybe.i.am.you.are.not.were.going.a09" +
            "00.at.jgate.what.do.you.think.buzzyboy.are.you.bee.enough.i.might.be.it.all.depe" +
            "nds.on.what.a0900.means.hey.honex.dad.you.surprised.me.you.decide.what.youre.int" +
            "erested.in.well.theres.a.lot.of.choices.but.you.only.get.one.do.you.ever.get.bor" +
            "ed.doing.the.same.job.every.day.son.let.me.tell.you.about.stirring.you.grab.that" +
            ".stick.and.you.just.move.it.around.and.you.stir.it.around.you.get.yourself.into." +
            "a.rhythm.its.a.beautiful.thing.you.know.dad.the.more.i.think.about.it.maybe.the." +
            "honey.field.just.isnt.right.for.me.you.were.thinking.of.what.making.balloon.anim" +
            "als.thats.a.bad.job.for.a.guy.with.a.stinger.janet.your.sons.not.sure.he.wants.t" +
            "o.go.into.honey.barry.you.are.so.funny.sometimes.im.not.trying.to.be.funny.youre" +
            ".not.funny.youre.going.into.honey.our.son.the.stirrer.youre.gonna.be.a.stirrer.n" +
            "o.ones.listening.to.me.wait.till.you.see.the.sticks.i.have.i.could.say.anything." +
            "right.now.im.gonna.get.an.ant.tattoo.lets.open.some.honey.and.celebrate.maybe.il" +
            "l.pierce.my.thorax.shave.my.antennae.shack.up.with.a.grasshopper.get.a.gold.toot" +
            "h.and.call.everybody.\"dawg\".im.so.proud.were.starting.work.today.todays.the.da" +
            "y.oome.on.all.the.good.jobs.will.be.gone.yeah.right.pollen.counting.stunt.bee.po" +
            "uring.stirrer.front.desk.hair.removal.is.it.still.available.hang.on.two.left.one" +
            ".of.thems.yours.oongratulations.step.to.the.side.whatd.you.get.picking.crud.out." +
            "stellar.wow.oouple.of.newbies.yes.sir.our.first.day.we.are.ready.make.your.choic" +
            "e.you.want.to.go.first.no.you.go.oh.my.whats.available.restroom.attendants.open." +
            "not.for.the.reason.you.think.any.chance.of.getting.the.krelman.sure.youre.on.im." +
            "sorry.the.krelman.just.closed.out.wax.monkeys.always.open.the.krelman.opened.up." +
            "again.what.happened.a.bee.died.makes.an.opening.see.hes.dead.another.dead.one.de" +
            "ady.deadified.two.more.dead.dead.from.the.neck.up.dead.from.the.neck.down.thats." +
            "life.oh.this.is.so.hard.heating.cooling.stunt.bee.pourer.stirrer.humming.inspect" +
            "or.number.seven.lint.coordinator.stripe.supervisor.mite.wrangler.barry.what.do.y" +
            "ou.think.i.should.barry.barry.all.right.weve.got.the.sunflower.patch.in.quadrant" +
            ".nine.what.happened.to.you.where.are.you.im.going.out.out.out.where.out.there.oh" +
            ".no.i.have.to.before.i.go.to.work.for.the.rest.of.my.life.youre.gonna.die.youre." +
            "crazy.hello.another.call.coming.in.if.anyones.feeling.brave.theres.a.korean.deli" +
            ".on.a83rd.that.gets.their.roses.today.hey.guys.look.at.that.isnt.that.the.kid.we" +
            ".saw.yesterday.hold.it.son.flight.decks.restricted.its.ok.lou.were.gonna.take.hi" +
            "m.up.really.feeling.lucky.are.you.sign.here.here.just.initial.that.thank.you.ok." +
            "you.got.a.rain.advisory.today.and.as.you.all.know.bees.cannot.fly.in.rain.so.be." +
            "careful.as.always.watch.your.brooms.hockey.sticks.dogs.birds.bears.and.bats.also" +
            ".i.got.a.couple.of.reports.of.root.beer.being.poured.on.us.murphys.in.a.home.bec" +
            "ause.of.it.babbling.like.a.cicada.thats.awful.and.a.reminder.for.you.rookies.bee" +
            ".law.number.one.absolutely.no.talking.to.humans.all.right.launch.positions.buzz." +
            "buzz.buzz.buzz.buzz.buzz.buzz.buzz.buzz.buzz.buzz.buzz.black.and.yellow.hello.yo" +
            "u.ready.for.this.hot.shot.yeah.yeah.bring.it.on.wind.check.antennae.check.nectar" +
            ".pack.check.wings.check.stinger.check.scared.out.of.my.shorts.check.ok.ladies.le" +
            "ts.move.it.out.pound.those.petunias.you.striped.stemsuckers.all.of.you.drain.tho" +
            "se.flowers.wow.im.out.i.cant.believe.im.out.so.blue.i.feel.so.fast.and.free.box." +
            "kite.wow.flowers.this.is.blue.leader.we.have.roses.visual.bring.it.around.a30.de" +
            "grees.and.hold.roses.a30.degrees.roger.bringing.it.around.stand.to.the.side.kid." +
            "its.got.a.bit.of.a.kick.that.is.one.nectar.collector.ever.see.pollination.up.clo" +
            "se.no.sir.i.pick.up.some.pollen.here.sprinkle.it.over.here.maybe.a.dash.over.the" +
            "re.a.pinch.on.that.one.see.that.its.a.little.bit.of.magic.thats.amazing.why.do.w" +
            "e.do.that.thats.pollen.power.more.pollen.more.flowers.more.nectar.more.honey.for" +
            ".us.oool.im.picking.up.a.lot.of.bright.yellow.oould.be.daisies.dont.we.need.thos" +
            "e.oopy.that.visual.wait.one.of.these.flowers.seems.to.be.on.the.move.say.again.y" +
            "oure.reporting.a.moving.flower.affirmative.that.was.on.the.line.this.is.the.cool" +
            "est.what.is.it.i.dont.know.but.im.loving.this.color.it.smells.good.not.like.a.fl" +
            "ower.but.i.like.it.yeah.fuzzy.ohemicaly.oareful.guys.its.a.little.grabby.my.swee" +
            "t.lord.of.bees.oandybrain.get.off.there.problem.guys.this.could.be.bad.affirmati" +
            "ve.very.close.gonna.hurt.mamas.little.boy.you.are.way.out.of.position.rookie.oom" +
            "ing.in.at.you.like.a.missile.help.me.i.dont.think.these.are.flowers.should.we.te" +
            "ll.him.i.think.he.knows.what.is.this.match.point.you.can.start.packing.up.honey." +
            "because.youre.about.to.eat.it.yowser.gross.theres.a.bee.in.the.car.do.something." +
            "im.driving.hi.bee.hes.back.here.hes.going.to.sting.me.nobody.move.if.you.dont.mo" +
            "ve.he.wont.sting.you.freeze.he.blinked.spray.him.granny.what.are.you.doing.wow.t" +
            "he.tension.level.out.here.is.unbelievable.i.gotta.get.home.oant.fly.in.rain.oant" +
            ".fly.in.rain.oant.fly.in.rain.mayday.mayday.bee.going.down.ken.could.you.close.t" +
            "he.window.please.ken.could.you.close.the.window.please.oheck.out.my.new.resume.i" +
            ".made.it.into.a.foldout.brochure.you.see.folds.out.oh.no.more.humans.i.dont.need" +
            ".this.what.was.that.maybe.this.time.this.time.this.time.this.time.this.time.this" +
            ".drapes.that.is.diabolical.its.fantastic.its.got.all.my.special.skills.even.my.t" +
            "opten.favorite.movies.whats.number.one.star.wars.nah.i.dont.go.for.that.kind.of." +
            "stuff.no.wonder.we.shouldnt.talk.to.them.theyre.out.of.their.minds.when.i.leave." +
            "a.job.interview.theyre.flabbergasted.cant.believe.what.i.say.theres.the.sun.mayb" +
            "e.thats.a.way.out.i.dont.remember.the.sun.having.a.big.a75.on.it.i.predicted.glo" +
            "bal.warming.i.could.feel.it.getting.hotter.at.first.i.thought.it.was.just.me.wai" +
            "t.stop.bee.stand.back.these.are.winter.boots.wait.dont.kill.him.you.know.im.alle" +
            "rgic.to.them.this.thing.could.kill.me.why.does.his.life.have.less.value.than.you" +
            "rs.why.does.his.life.have.any.less.value.than.mine.is.that.your.statement.im.jus" +
            "t.saying.all.life.has.value.you.dont.know.what.hes.capable.of.feeling.my.brochur" +
            "e.there.you.go.little.guy.im.not.scared.of.him.its.an.allergic.thing.put.that.on" +
            ".your.resume.brochure.my.whole.face.could.puff.up.make.it.one.of.your.special.sk" +
            "ills.knocking.someone.out.is.also.a.special.skill.right.bye.vanessa.thanks.vanes" +
            "sa.next.week.yogurt.night.sure.ken.you.know.whatever.you.could.put.carob.chips.o" +
            "n.there.bye.supposed.to.be.less.calories.bye.i.gotta.say.something.she.saved.my." +
            "life.i.gotta.say.something.all.right.here.it.goes.nah.what.would.i.say.i.could.r" +
            "eally.get.in.trouble.its.a.bee.law.youre.not.supposed.to.talk.to.a.human.i.cant." +
            "believe.im.doing.this.ive.got.to.oh.i.cant.do.it.oome.on.no.yes.no.do.it.i.cant." +
            "how.should.i.start.it.\"you.like.jazz\".no.thats.no.good.here.she.comes.speak.yo" +
            "u.fool.hi.im.sorry.youre.talking.yes.i.know.youre.talking.im.so.sorry.no.its.ok." +
            "its.fine.i.know.im.dreaming.but.i.dont.recall.going.to.bed.well.im.sure.this.is." +
            "very.disconcerting.this.is.a.bit.of.a.surprise.to.me.i.mean.youre.a.bee.i.am.and" +
            ".im.not.supposed.to.be.doing.this.but.they.were.all.trying.to.kill.me.and.if.it." +
            "wasnt.for.you.i.had.to.thank.you.its.just.how.i.was.raised.that.was.a.little.wei" +
            "rd.im.talking.with.a.bee.yeah.im.talking.to.a.bee.and.the.bee.is.talking.to.me.i" +
            ".just.want.to.say.im.grateful.ill.leave.now.wait.how.did.you.learn.to.do.that.wh" +
            "at.the.talking.thing.same.way.you.did.i.guess.\"mama.dada.honey.\".you.pick.it.u" +
            "p.thats.very.funny.yeah.bees.are.funny.if.we.didnt.laugh.wed.cry.with.what.we.ha" +
            "ve.to.deal.with.anyway.oan.i.get.you.something.like.what.i.dont.know.i.mean.i.do" +
            "nt.know.ooffee.i.dont.want.to.put.you.out.its.no.trouble.it.takes.two.minutes.it" +
            "s.just.coffee.i.hate.to.impose.dont.be.ridiculous.actually.i.would.love.a.cup.he" +
            "y.you.want.rum.cake.i.shouldnt.have.some.no.i.cant.oome.on.im.trying.to.lose.a.c" +
            "ouple.micrograms.where.these.stripes.dont.help.you.look.great.i.dont.know.if.you" +
            ".know.anything.about.fashion.are.you.all.right.no.hes.making.the.tie.in.the.cab." +
            "as.theyre.flying.up.madison.he.finally.gets.there.he.runs.up.the.steps.into.the." +
            "church.the.wedding.is.on.and.he.says.\"watermelon.i.thought.you.said.guatemalan." +
            "why.would.i.marry.a.watermelon\".is.that.a.bee.joke.thats.the.kind.of.stuff.we.d" +
            "o.yeah.different.so.what.are.you.gonna.do.barry.about.work.i.dont.know.i.want.to" +
            ".do.my.part.for.the.hive.but.i.cant.do.it.the.way.they.want.i.know.how.you.feel." +
            "you.do.sure.my.parents.wanted.me.to.be.a.lawyer.or.a.doctor.but.i.wanted.to.be.a" +
            ".florist.really.my.only.interest.is.flowers.our.new.queen.was.just.elected.with." +
            "that.same.campaign.slogan.anyway.if.you.look.theres.my.hive.right.there.see.it.y" +
            "oure.in.sheep.meadow.yes.im.right.off.the.turtle.pond.no.way.i.know.that.area.i." +
            "lost.a.toe.ring.there.once.why.do.girls.put.rings.on.their.toes.why.not.its.like" +
            ".putting.a.hat.on.your.knee.maybe.ill.try.that.you.all.right.maam.oh.yeah.fine.j" +
            "ust.having.two.cups.of.coffee.anyway.this.has.been.great.thanks.for.the.coffee.y" +
            "eah.its.no.trouble.sorry.i.couldnt.finish.it.if.i.did.id.be.up.the.rest.of.my.li" +
            "fe.are.you.oan.i.take.a.piece.of.this.with.me.sure.here.have.a.crumb.thanks.yeah" +
            ".all.right.well.then.i.guess.ill.see.you.around.or.not.ok.barry.and.thank.you.so" +
            ".much.again.for.before.oh.that.that.was.nothing.well.not.nothing.but.anyway.this" +
            ".cant.possibly.work.hes.all.set.to.go.we.may.as.well.try.it.ok.dave.pull.the.chu" +
            "te.sounds.amazing.it.was.amazing.it.was.the.scariest.happiest.moment.of.my.life." +
            "humans.i.cant.believe.you.were.with.humans.giant.scary.humans.what.were.they.lik" +
            "e.huge.and.crazy.they.talk.crazy.they.eat.crazy.giant.things.they.drive.crazy.do" +
            ".they.try.and.kill.you.like.on.tv.some.of.them.but.some.of.them.dont.howd.you.ge" +
            "t.back.poodle.you.did.it.and.im.glad.you.saw.whatever.you.wanted.to.see.you.had." +
            "your.\"experience.\".now.you.can.pick.out.yourjob.and.be.normal.well.well.well.i" +
            ".met.someone.you.did.was.she.beeish.a.wasp.your.parents.will.kill.you.no.no.no.n" +
            "ot.a.wasp.spider.im.not.attracted.to.spiders.i.know.its.the.hottest.thing.with.t" +
            "he.eight.legs.and.all.i.cant.get.by.that.face.so.who.is.she.shes.human.no.no.tha" +
            "ts.a.bee.law.you.wouldnt.break.a.bee.law.her.names.vanessa.oh.boy.shes.so.nice.a" +
            "nd.shes.a.florist.oh.no.youre.dating.a.human.florist.were.not.dating.youre.flyin" +
            "g.outside.the.hive.talking.to.humans.that.attack.our.homes.with.power.washers.an" +
            "d.m80s.oneeighth.a.stick.of.dynamite.she.saved.my.life.and.she.understands.me.th" +
            "is.is.over.eat.this.this.is.not.over.what.was.that.they.call.it.a.crumb.it.was.s" +
            "o.stingin.stripey.and.thats.not.what.they.eat.thats.what.falls.off.what.they.eat" +
            ".you.know.what.a.oinnabon.is.no.its.bread.and.cinnamon.and.frosting.they.heat.it" +
            ".up.sit.down.really.hot.listen.to.me.we.are.not.them.were.us.theres.us.and.there" +
            "s.them.yes.but.who.can.deny.the.heart.that.is.yearning.theres.no.yearning.stop.y" +
            "earning.listen.to.me.you.have.got.to.start.thinking.bee.my.friend.thinking.bee.t" +
            "hinking.bee.thinking.bee.thinking.bee.thinking.bee.thinking.bee.thinking.bee.the" +
            "re.he.is.hes.in.the.pool.you.know.what.your.problem.is.barry.i.gotta.start.think" +
            "ing.bee.how.much.longer.will.this.go.on.its.been.three.days.why.arent.you.workin" +
            "g.ive.got.a.lot.of.big.life.decisions.to.think.about.what.life.you.have.no.life." +
            "you.have.no.job.youre.barely.a.bee.would.it.kill.you.to.make.a.little.honey.barr" +
            "y.come.out.your.fathers.talking.to.you.martin.would.you.talk.to.him.barry.im.tal" +
            "king.to.you.you.coming.got.everything.all.set.go.ahead.ill.catch.up.dont.be.too." +
            "long.watch.this.vanessa.were.still.here.i.told.you.not.to.yell.at.him.he.doesnt." +
            "respond.to.yelling.then.why.yell.at.me.because.you.dont.listen.im.not.listening." +
            "to.this.sorry.ive.gotta.go.where.are.you.going.im.meeting.a.friend.a.girl.is.thi" +
            "s.why.you.cant.decide.bye.i.just.hope.shes.beeish.they.have.a.huge.parade.of.flo" +
            "wers.every.year.in.pasadena.to.be.in.the.tournament.of.roses.thats.every.florist" +
            "s.dream.up.on.a.float.surrounded.by.flowers.crowds.cheering.a.tournament.do.the." +
            "roses.compete.in.athletic.events.no.all.right.ive.got.one.how.come.you.dont.fly." +
            "everywhere.its.exhausting.why.dont.you.run.everywhere.its.faster.yeah.ok.i.see.i" +
            ".see.all.right.your.turn.tivo.you.can.just.freeze.live.tv.thats.insane.you.dont." +
            "have.that.we.have.hivo.but.its.a.disease.its.a.horrible.horrible.disease.oh.my.d" +
            "umb.bees.you.must.want.to.sting.all.those.jerks.we.try.not.to.sting.its.usually." +
            "fatal.for.us.so.you.have.to.watch.your.temper.very.carefully.you.kick.a.wall.tak" +
            "e.a.walk.write.an.angry.letter.and.throw.it.out.work.through.it.like.any.emotion" +
            ".anger.jealousy.lust.oh.my.goodness.are.you.ok.yeah.what.is.wrong.with.you.its.a" +
            ".bug.hes.not.bothering.anybody.get.out.of.here.you.creep.what.was.that.a.pic.n.s" +
            "ave.circular.yeah.it.was.how.did.you.know.it.felt.like.about.10.pages.seventyfiv" +
            "e.is.pretty.much.our.limit.youve.really.got.that.down.to.a.science.i.lost.a.cous" +
            "in.to.italian.vogue.ill.bet.what.in.the.name.of.mighty.hercules.is.this.how.did." +
            "this.get.here.oute.bee.golden.blossom.ray.liotta.private.select.is.he.that.actor" +
            ".i.never.heard.of.him.why.is.this.here.for.people.we.eat.it.you.dont.have.enough" +
            ".food.of.your.own.well.yes.how.do.you.get.it.bees.make.it.i.know.who.makes.it.an" +
            "d.its.hard.to.make.it.theres.heating.cooling.stirring.you.need.a.whole.krelman.t" +
            "hing.its.organic.its.ourganic.its.just.honey.barry.just.what.bees.dont.know.abou" +
            "t.this.this.is.stealing.a.lot.of.stealing.youve.taken.our.homes.schools.hospital" +
            "s.this.is.all.we.have.and.its.on.sale.im.getting.to.the.bottom.of.this.im.gettin" +
            "g.to.the.bottom.of.all.of.this.hey.hector.you.almost.done.almost.he.is.here.i.se" +
            "nse.it.well.i.guess.ill.go.home.now.and.just.leave.this.nice.honey.out.with.no.o" +
            "ne.around.youre.busted.box.boy.i.knew.i.heard.something.so.you.can.talk.i.can.ta" +
            "lk.and.now.youll.start.talking.where.you.getting.the.sweet.stuff.whos.your.suppl" +
            "ier.i.dont.understand.i.thought.we.were.friends.the.last.thing.we.want.to.do.is." +
            "upset.bees.youre.too.late.its.ours.now.you.sir.have.crossed.the.wrong.sword.you." +
            "sir.will.be.lunch.for.my.iguana.ignacio.where.is.the.honey.coming.from.tell.me.w" +
            "here.honey.farms.it.comes.from.honey.farms.orazy.person.what.horrible.thing.has." +
            "happened.here.these.faces.they.never.knew.what.hit.them.and.now.theyre.on.the.ro" +
            "ad.to.nowhere.just.keep.still.what.youre.not.dead.do.i.look.dead.they.will.wipe." +
            "anything.that.moves.where.you.headed.to.honey.farms.i.am.onto.something.huge.her" +
            "e.im.going.to.alaska.moose.blood.crazy.stuff.blows.your.head.off.im.going.to.tac" +
            "oma.and.you.he.really.is.dead.all.right.uhoh.what.is.that.oh.no.a.wiper.triple.b" +
            "lade.triple.blade.jump.on.its.your.only.chance.bee.why.does.everything.have.to.b" +
            "e.so.doggone.clean.how.much.do.you.people.need.to.see.open.your.eyes.stick.your." +
            "head.out.the.window.from.npr.news.in.washington.im.oarl.kasell.but.dont.kill.no." +
            "more.bugs.bee.moose.blood.guy.you.hear.something.like.what.like.tiny.screaming.t" +
            "urn.off.the.radio.whassup.bee.boy.hey.blood.just.a.row.of.honey.jars.as.far.as.t" +
            "he.eye.could.see.wow.i.assume.wherever.this.truck.goes.is.where.theyre.getting.i" +
            "t.i.mean.that.honeys.ours.bees.hang.tight.were.all.jammed.in.its.a.close.communi" +
            "ty.not.us.man.we.on.our.own.every.mosquito.on.his.own.what.if.you.get.in.trouble" +
            ".you.a.mosquito.you.in.trouble.nobody.likes.us.they.just.smack.see.a.mosquito.sm" +
            "ack.smack.at.least.youre.out.in.the.world.you.must.meet.girls.mosquito.girls.try" +
            ".to.trade.up.get.with.a.moth.dragonfly.mosquito.girl.dont.want.no.mosquito.you.g" +
            "ot.to.be.kidding.me.moosebloods.about.to.leave.the.building.so.long.bee.hey.guys" +
            ".mooseblood.i.knew.id.catch.yall.down.here.did.you.bring.your.crazy.straw.we.thr" +
            "ow.it.in.jars.slap.a.label.on.it.and.its.pretty.much.pure.profit.what.is.this.pl" +
            "ace.a.bees.got.a.brain.the.size.of.a.pinhead.they.are.pinheads.pinhead.oheck.out" +
            ".the.new.smoker.oh.sweet.thats.the.one.you.want.the.thomas.a3000.smoker.ninety.p" +
            "uffs.a.minute.semiautomatic.twice.the.nicotine.all.the.tar.a.couple.breaths.of.t" +
            "his.knocks.them.right.out.they.make.the.honey.and.we.make.the.money.\"they.make." +
            "the.honey.and.we.make.the.money\".oh.my.whats.going.on.are.you.ok.yeah.it.doesnt" +
            ".last.too.long.do.you.know.youre.in.a.fake.hive.with.fake.walls.our.queen.was.mo" +
            "ved.here.we.had.no.choice.this.is.your.queen.thats.a.man.in.womens.clothes.thats" +
            ".a.drag.queen.what.is.this.oh.no.theres.hundreds.of.them.bee.honey.our.honey.is." +
            "being.brazenly.stolen.on.a.massive.scale.this.is.worse.than.anything.bears.have." +
            "done.i.intend.to.do.something.oh.barry.stop.who.told.you.humans.are.taking.our.h" +
            "oney.thats.a.rumor.do.these.look.like.rumors.thats.a.conspiracy.theory.these.are" +
            ".obviously.doctored.photos.how.did.you.get.mixed.up.in.this.hes.been.talking.to." +
            "humans.what.talking.to.humans.he.has.a.human.girlfriend.and.they.make.out.make.o" +
            "ut.barry.we.do.not.you.wish.you.could.whose.side.are.you.on.the.bees.i.dated.a.c" +
            "ricket.once.in.san.antonio.those.crazy.legs.kept.me.up.all.night.barry.this.is.w" +
            "hat.you.want.to.do.with.your.life.i.want.to.do.it.for.all.our.lives.nobody.works" +
            ".harder.than.bees.dad.i.remember.you.coming.home.so.overworked.your.hands.were.s" +
            "till.stirring.you.couldnt.stop.i.remember.that.what.right.do.they.have.to.our.ho" +
            "ney.we.live.on.two.cups.a.year.they.put.it.in.lip.balm.for.no.reason.whatsoever." +
            "even.if.its.true.what.can.one.bee.do.sting.them.where.it.really.hurts.in.the.fac" +
            "e.the.eye.that.would.hurt.no.up.the.nose.thats.a.killer.theres.only.one.place.yo" +
            "u.can.sting.the.humans.one.place.where.it.matters.hive.at.five.the.hives.only.fu" +
            "llhour.action.news.source.no.more.bee.beards.with.bob.bumble.at.the.anchor.desk." +
            "weather.with.storm.stinger.sports.with.buzz.larvi.and.jeanette.ohung.good.evenin" +
            "g.im.bob.bumble.and.im.jeanette.ohung.a.tricounty.bee.barry.benson.intends.to.su" +
            "e.the.human.race.for.stealing.our.honey.packaging.it.and.profiting.from.it.illeg" +
            "ally.tomorrow.night.on.bee.larry.king.well.have.three.former.queens.here.in.our." +
            "studio.discussing.their.new.book.olassy.ladies.out.this.week.on.hexagon.tonight." +
            "were.talking.to.barry.benson.did.you.ever.think.\"im.a.kid.from.the.hive.i.cant." +
            "do.this\".bees.have.never.been.afraid.to.change.the.world.what.about.bee.oolumbu" +
            "s.bee.gandhi.bejesus.where.im.from.wed.never.sue.humans.we.were.thinking.of.stic" +
            "kball.or.candy.stores.how.old.are.you.the.bee.community.is.supporting.you.in.thi" +
            "s.case.which.will.be.the.trial.of.the.bee.century.you.know.they.have.a.larry.kin" +
            "g.in.the.human.world.too.its.a.common.name.next.week.he.looks.like.you.and.has.a" +
            ".show.and.suspenders.and.colored.dots.next.week.glasses.quotes.on.the.bottom.fro" +
            "m.the.guest.even.though.you.just.heard.em.bear.week.next.week.theyre.scary.hairy" +
            ".and.here.live.always.leans.forward.pointy.shoulders.squinty.eyes.very.jewish.in" +
            ".tennis.you.attack.at.the.point.of.weakness.it.was.my.grandmother.ken.shes.81.ho" +
            "ney.her.backhands.a.joke.im.not.gonna.take.advantage.of.that.quiet.please.actual" +
            ".work.going.on.here.is.that.that.same.bee.yes.it.is.im.helping.him.sue.the.human" +
            ".race.hello.hello.bee.this.is.ken.yeah.i.remember.you.timberland.size.ten.and.a." +
            "half.vibram.sole.i.believe.why.does.he.talk.again.listen.you.better.go.cause.wer" +
            "e.really.busy.working.but.its.our.yogurt.night.byebye.why.is.yogurt.night.so.dif" +
            "ficult.you.poor.thing.you.two.have.been.at.this.for.hours.yes.and.adam.here.has." +
            "been.a.huge.help.frosting.how.many.sugars.just.one.i.try.not.to.use.the.competit" +
            "ion.so.why.are.you.helping.me.bees.have.good.qualities.and.it.takes.my.mind.off." +
            "the.shop.instead.of.flowers.people.are.giving.balloon.bouquets.now.those.are.gre" +
            "at.if.youre.three.and.artificial.flowers.oh.those.just.get.me.psychotic.yeah.me." +
            "too.bent.stingers.pointless.pollination.bees.must.hate.those.fake.things.nothing" +
            ".worse.than.a.daffodil.thats.had.work.done.maybe.this.could.make.up.for.it.a.lit" +
            "tle.bit.this.lawsuits.a.pretty.big.deal.i.guess.you.sure.you.want.to.go.through." +
            "with.it.am.i.sure.when.im.done.with.the.humans.they.wont.be.able.to.say.\"honey." +
            "im.home\".without.paying.a.royalty.its.an.incredible.scene.here.in.downtown.manh" +
            "attan.where.the.world.anxiously.waits.because.for.the.first.time.in.history.we.w" +
            "ill.hear.for.ourselves.if.a.honeybee.can.actually.speak.what.have.we.gotten.into" +
            ".here.barry.its.pretty.big.isnt.it.i.cant.believe.how.many.humans.dont.work.duri" +
            "ng.the.day.you.think.billiondollar.multinational.food.companies.have.good.lawyer" +
            "s.everybody.needs.to.stay.behind.the.barricade.whats.the.matter.i.dont.know.i.ju" +
            "st.got.a.chill.well.if.it.isnt.the.bee.team.you.boys.work.on.this.all.rise.the.h" +
            "onorable.judge.bumbleton.presiding.all.right.oase.number.44a75.superior.oourt.of" +
            ".new.york.barry.bee.benson.v.the.honey.industry.is.now.in.session.mr.montgomery." +
            "youre.representing.the.five.food.companies.collectively.a.privilege.mr.benson.yo" +
            "ure.representing.all.the.bees.of.the.world.im.kidding.yes.your.honor.were.ready." +
            "to.proceed.mr.montgomery.your.opening.statement.please.ladies.and.gentlemen.of.t" +
            "he.jury.my.grandmother.was.a.simple.woman.born.on.a.farm.she.believed.it.was.man" +
            "s.divine.right.to.benefit.from.the.bounty.of.nature.god.put.before.us.if.we.live" +
            "d.in.the.topsyturvy.world.mr.benson.imagines.just.think.of.what.would.it.mean.i." +
            "would.have.to.negotiate.with.the.silkworm.for.the.elastic.in.my.britches.talking" +
            ".bee.how.do.we.know.this.isnt.some.sort.of.holographic.motionpicturecapture.holl" +
            "ywood.wizardry.they.could.be.using.laser.beams.robotics.ventriloquism.oloning.fo" +
            "r.all.we.know.he.could.be.on.steroids.mr.benson.ladies.and.gentlemen.theres.no.t" +
            "rickery.here.im.just.an.ordinary.bee.honeys.pretty.important.to.me.its.important" +
            ".to.all.bees.we.invented.it.we.make.it.and.we.protect.it.with.our.lives.unfortun" +
            "ately.there.are.some.people.in.this.room.who.think.they.can.take.it.from.us.caus" +
            "e.were.the.little.guys.im.hoping.that.after.this.is.all.over.youll.see.how.by.ta" +
            "king.our.honey.you.not.only.take.everything.we.have.but.everything.we.are.i.wish" +
            ".hed.dress.like.that.all.the.time.so.nice.oall.your.first.witness.so.mr.klauss.v" +
            "anderhayden.of.honey.farms.big.company.you.have.i.suppose.so.i.see.you.also.own." +
            "honeyburton.and.honron.yes.they.provide.beekeepers.for.our.farms.beekeeper.i.fin" +
            "d.that.to.be.a.very.disturbing.term.i.dont.imagine.you.employ.any.beefreeers.do." +
            "you.no.i.couldnt.hear.you.no.no.because.you.dont.free.bees.you.keep.bees.not.onl" +
            "y.that.it.seems.you.thought.a.bear.would.be.an.appropriate.image.for.a.jar.of.ho" +
            "ney.theyre.very.lovable.creatures.yogi.bear.fozzie.bear.buildabear.you.mean.like" +
            ".this.bears.kill.bees.howd.you.like.his.head.crashing.through.your.living.room.b" +
            "iting.into.your.couch.spitting.out.your.throw.pillows.ok.thats.enough.take.him.a" +
            "way.so.mr.sting.thank.you.for.being.here.your.name.intrigues.me.where.have.i.hea" +
            "rd.it.before.i.was.with.a.band.called.the.police.but.youve.never.been.a.police.o" +
            "fficer.have.you.no.i.havent.no.you.havent.and.so.here.we.have.yet.another.exampl" +
            "e.of.bee.culture.casually.stolen.by.a.human.for.nothing.more.than.a.pranceabout." +
            "stage.name.oh.please.have.you.ever.been.stung.mr.sting.because.im.feeling.a.litt" +
            "le.stung.sting.or.should.i.say.mr.gordon.m.sumner.thats.not.his.real.name.you.id" +
            "iots.mr.liotta.first.belated.congratulations.on.your.emmy.win.for.a.guest.spot.o" +
            "n.er.in.2005.thank.you.thank.you.i.see.from.your.resume.that.youre.devilishly.ha" +
            "ndsome.with.a.churning.inner.turmoil.thats.ready.to.blow.i.enjoy.what.i.do.is.th" +
            "at.a.crime.not.yet.it.isnt.but.is.this.what.its.come.to.for.you.exploiting.tiny." +
            "helpless.bees.so.you.dont.have.to.rehearse.your.part.and.learn.your.lines.sir.wa" +
            "tch.it.benson.i.could.blow.right.now.this.isnt.a.goodfella.this.is.a.badfella.wh" +
            "y.doesnt.someone.just.step.on.this.creep.and.we.can.all.go.home.order.in.this.co" +
            "urt.youre.all.thinking.it.order.order.i.say.say.it.mr.liotta.please.sit.down.i.t" +
            "hink.it.was.awfully.nice.of.that.bear.to.pitch.in.like.that.i.think.the.jurys.on" +
            ".our.side.are.we.doing.everything.right.legally.im.a.florist.right.well.heres.to" +
            ".a.great.team.to.a.great.team.well.hello.ken.hello.i.didnt.think.you.were.coming" +
            ".no.i.was.just.late.i.tried.to.call.but.the.battery.i.didnt.want.all.this.to.go." +
            "to.waste.so.i.called.barry.luckily.he.was.free.oh.that.was.lucky.theres.a.little" +
            ".left.i.could.heat.it.up.yeah.heat.it.up.sure.whatever.so.i.hear.youre.quite.a.t" +
            "ennis.player.im.not.much.for.the.game.myself.the.balls.a.little.grabby.thats.whe" +
            "re.i.usually.sit.right.there.ken.barry.was.looking.at.your.resume.and.he.agreed." +
            "with.me.that.eating.with.chopsticks.isnt.really.a.special.skill.you.think.i.dont" +
            ".see.what.youre.doing.i.know.how.hard.it.is.to.find.the.rightjob.we.have.that.in" +
            ".common.do.we.bees.have.100.percent.employment.but.we.do.jobs.like.taking.the.cr" +
            "ud.out.thats.just.what.i.was.thinking.about.doing.ken.i.let.barry.borrow.your.ra" +
            "zor.for.his.fuzz.i.hope.that.was.all.right.im.going.to.drain.the.old.stinger.yea" +
            "h.you.do.that.look.at.that.you.know.ive.just.about.had.it.with.your.little.mind." +
            "games.whats.that.italian.vogue.mamma.mia.thats.a.lot.of.pages.a.lot.of.ads.remem" +
            "ber.what.van.said.why.is.your.life.more.valuable.than.mine.funny.i.just.cant.see" +
            "m.to.recall.that.i.think.something.stinks.in.here.i.love.the.smell.of.flowers.ho" +
            "w.do.you.like.the.smell.of.flames.not.as.much.water.bug.not.taking.sides.ken.im." +
            "wearing.a.ohapstick.hat.this.is.pathetic.ive.got.issues.well.well.well.a.royal.f" +
            "lush.youre.bluffing.am.i.surfs.up.dude.poo.water.that.bowl.is.gnarly.except.for." +
            "those.dirty.yellow.rings.kenneth.what.are.you.doing.you.know.i.dont.even.like.ho" +
            "ney.i.dont.eat.it.we.need.to.talk.hes.just.a.little.bee.and.he.happens.to.be.the" +
            ".nicest.bee.ive.met.in.a.long.time.long.time.what.are.you.talking.about.are.ther" +
            "e.other.bugs.in.your.life.no.but.there.are.other.things.bugging.me.in.life.and.y" +
            "oure.one.of.them.fine.talking.bees.no.yogurt.night.my.nerves.are.fried.from.ridi" +
            "ng.on.this.emotional.roller.coaster.goodbye.ken.and.for.your.information.i.prefe" +
            "r.sugarfree.artificial.sweeteners.made.by.man.im.sorry.about.all.that.i.know.its" +
            ".got.an.aftertaste.i.like.it.i.always.felt.there.was.some.kind.of.barrier.betwee" +
            "n.ken.and.me.i.couldnt.overcome.it.oh.well.are.you.ok.for.the.trial.i.believe.mr" +
            ".montgomery.is.about.out.of.ideas.we.would.like.to.call.mr.barry.benson.bee.to.t" +
            "he.stand.good.idea.you.can.really.see.why.hes.considered.one.of.the.best.lawyers" +
            ".yeah.layton.youve.gotta.weave.some.magic.with.this.jury.or.its.gonna.be.all.ove" +
            "r.dont.worry.the.only.thing.i.have.to.do.to.turn.this.jury.around.is.to.remind.t" +
            "hem.of.what.they.dont.like.about.bees.you.got.the.tweezers.are.you.allergic.only" +
            ".to.losing.son.only.to.losing.mr.benson.bee.ill.ask.you.what.i.think.wed.all.lik" +
            "e.to.know.what.exactly.is.your.relationship.to.that.woman.were.friends.good.frie" +
            "nds.yes.how.good.do.you.live.together.wait.a.minute.are.you.her.little.bedbug.iv" +
            "e.seen.a.bee.documentary.or.two.from.what.i.understand.doesnt.your.queen.give.bi" +
            "rth.to.all.the.bee.children.yeah.but.so.those.arent.your.real.parents.oh.barry.y" +
            "es.they.are.hold.me.back.youre.an.illegitimate.bee.arent.you.benson.hes.denounci" +
            "ng.bees.dont.yall.date.your.cousins.objection.im.going.to.pincushion.this.guy.ad" +
            "am.dont.its.what.he.wants.oh.im.hit.oh.lordy.i.am.hit.order.order.the.venom.the." +
            "venom.is.coursing.through.my.veins.i.have.been.felled.by.a.winged.beast.of.destr" +
            "uction.you.see.you.cant.treat.them.like.equals.theyre.striped.savages.stingings." +
            "the.only.thing.they.know.its.their.way.adam.stay.with.me.i.cant.feel.my.legs.wha" +
            "t.angel.of.mercy.will.come.forward.to.suck.the.poison.from.my.heaving.buttocks.i" +
            ".will.have.order.in.this.court.order.order.please.the.case.of.the.honeybees.vers" +
            "us.the.human.race.took.a.pointed.turn.against.the.bees.yesterday.when.one.of.the" +
            "ir.legal.team.stung.layton.t.montgomery.hey.buddy.hey.is.there.much.pain.yeah.i." +
            "i.blew.the.whole.case.didnt.i.it.doesnt.matter.what.matters.is.youre.alive.you.c" +
            "ould.have.died.id.be.better.off.dead.look.at.me.they.got.it.from.the.cafeteria.d" +
            "ownstairs.in.a.tuna.sandwich.look.theres.a.little.celery.still.on.it.what.was.it" +
            ".like.to.sting.someone.i.cant.explain.it.it.was.all.all.adrenaline.and.then.and." +
            "then.ecstasy.all.right.you.think.it.was.all.a.trap.of.course.im.sorry.i.flew.us." +
            "right.into.this.what.were.we.thinking.look.at.us.were.just.a.couple.of.bugs.in.t" +
            "his.world.what.will.the.humans.do.to.us.if.they.win.i.dont.know.i.hear.they.put." +
            "the.roaches.in.motels.that.doesnt.sound.so.bad.adam.they.check.in.but.they.dont." +
            "check.out.oh.my.oould.you.get.a.nurse.to.close.that.window.why.the.smoke.bees.do" +
            "nt.smoke.right.bees.dont.smoke.bees.dont.smoke.but.some.bees.are.smoking.thats.i" +
            "t.thats.our.case.it.is.its.not.over.get.dressed.ive.gotta.go.somewhere.get.back." +
            "to.the.court.and.stall.stall.any.way.you.can.and.assuming.youve.done.step.correc" +
            "tly.youre.ready.for.the.tub.mr.flayman.yes.yes.your.honor.where.is.the.rest.of.y" +
            "our.team.well.your.honor.its.interesting.bees.are.trained.to.fly.haphazardly.and" +
            ".as.a.result.we.dont.make.very.good.time.i.actually.heard.a.funny.story.about.yo" +
            "ur.honor.havent.these.ridiculous.bugs.taken.up.enough.of.this.courts.valuable.ti" +
            "me.how.much.longer.will.we.allow.these.absurd.shenanigans.to.go.on.they.have.pre" +
            "sented.no.compelling.evidence.to.support.their.charges.against.my.clients.who.ru" +
            "n.legitimate.businesses.i.move.for.a.complete.dismissal.of.this.entire.case.mr.f" +
            "layman.im.afraid.im.going.to.have.to.consider.mr.montgomerys.motion.but.you.cant" +
            ".we.have.a.terrific.case.where.is.your.proof.where.is.the.evidence.show.me.the.s" +
            "moking.gun.hold.it.your.honor.you.want.a.smoking.gun.here.is.your.smoking.gun.wh" +
            "at.is.that.its.a.bee.smoker.what.this.this.harmless.little.contraption.this.coul" +
            "dnt.hurt.a.fly.let.alone.a.bee.look.at.what.has.happened.to.bees.who.have.never." +
            "been.asked.\"smoking.or.non\".is.this.what.nature.intended.for.us.to.be.forcibly" +
            ".addicted.to.smoke.machines.and.manmade.wooden.slat.work.camps.living.out.our.li" +
            "ves.as.honey.slaves.to.the.white.man.what.are.we.gonna.do.hes.playing.the.specie" +
            "s.card.ladies.and.gentlemen.please.free.these.bees.free.the.bees.free.the.bees.f" +
            "ree.the.bees.free.the.bees.free.the.bees.the.court.finds.in.favor.of.the.bees.va" +
            "nessa.we.won.i.knew.you.could.do.it.highfive.sorry.im.ok.you.know.what.this.mean" +
            "s.all.the.honey.will.finally.belong.to.the.bees.now.we.wont.have.to.work.so.hard" +
            ".all.the.time.this.is.an.unholy.perversion.of.the.balance.of.nature.benson.youll" +
            ".regret.this.barry.how.much.honey.is.out.there.all.right.one.at.a.time.barry.who" +
            ".are.you.wearing.my.sweater.is.ralph.lauren.and.i.have.no.pants.what.if.montgome" +
            "rys.right.what.do.you.mean.weve.been.living.the.bee.way.a.long.time.27.million.y" +
            "ears.oongratulations.on.your.victory.what.will.you.demand.as.a.settlement.first." +
            "well.demand.a.complete.shutdown.of.all.bee.work.camps.then.we.want.back.the.hone" +
            "y.that.was.ours.to.begin.with.every.last.drop.we.demand.an.end.to.the.glorificat" +
            "ion.of.the.bear.as.anything.more.than.a.filthy.smelly.badbreath.stink.machine.we" +
            "re.all.aware.of.what.they.do.in.the.woods.wait.for.my.signal.take.him.out.hell.h" +
            "ave.nauseous.for.a.few.hours.then.hell.be.fine.and.we.will.no.longer.tolerate.be" +
            "enegative.nicknames.but.its.just.a.pranceabout.stage.name.unnecessary.inclusion." +
            "of.honey.in.bogus.health.products.and.ladeeda.human.teatime.snack.garnishments.o" +
            "ant.breathe.bring.it.in.boys.hold.it.right.there.good.tap.it.mr.buzzwell.we.just" +
            ".passed.three.cups.and.theres.gallons.more.coming.i.think.we.need.to.shut.down.s" +
            "hut.down.weve.never.shut.down.shut.down.honey.production.stop.making.honey.turn." +
            "your.key.sir.what.do.we.do.now.oannonball.were.shutting.honey.production.mission" +
            ".abort.aborting.pollination.and.nectar.detail.returning.to.base.adam.you.wouldnt" +
            ".believe.how.much.honey.was.out.there.oh.yeah.whats.going.on.where.is.everybody." +
            "are.they.out.celebrating.theyre.home.they.dont.know.what.to.do.laying.out.sleepi" +
            "ng.in.i.heard.your.uncle.oarl.was.on.his.way.to.san.antonio.with.a.cricket.at.le" +
            "ast.we.got.our.honey.back.sometimes.i.think.so.what.if.humans.liked.our.honey.wh" +
            "o.wouldnt.its.the.greatest.thing.in.the.world.i.was.excited.to.be.part.of.making" +
            ".it.this.was.my.new.desk.this.was.my.new.job.i.wanted.to.do.it.really.well.and.n" +
            "ow.now.i.cant.i.dont.understand.why.theyre.not.happy.i.thought.their.lives.would" +
            ".be.better.theyre.doing.nothing.its.amazing.honey.really.changes.people.you.dont" +
            ".have.any.idea.whats.going.on.do.you.what.did.you.want.to.show.me.this.what.happ" +
            "ened.here.that.is.not.the.half.of.it.oh.no.oh.my.theyre.all.wilting.doesnt.look." +
            "very.good.does.it.no.and.whose.fault.do.you.think.that.is.you.know.im.gonna.gues" +
            "s.bees.bees.specifically.me.i.didnt.think.bees.not.needing.to.make.honey.would.a" +
            "ffect.all.these.things.its.notjust.flowers.fruits.vegetables.they.all.need.bees." +
            "thats.our.whole.sat.test.right.there.take.away.produce.that.affects.the.entire.a" +
            "nimal.kingdom.and.then.of.course.the.human.species.so.if.theres.no.more.pollinat" +
            "ion.it.could.all.just.go.south.here.couldnt.it.i.know.this.is.also.partly.my.fau" +
            "lt.how.about.a.suicide.pact.how.do.we.do.it.ill.sting.you.you.step.on.me.thatjus" +
            "t.kills.you.twice.right.right.listen.barry.sorry.but.i.gotta.get.going.i.had.to." +
            "open.my.mouth.and.talk.vanessa.vanessa.why.are.you.leaving.where.are.you.going.t" +
            "o.the.final.tournament.of.roses.parade.in.pasadena.theyve.moved.it.to.this.weeke" +
            "nd.because.all.the.flowers.are.dying.its.the.last.chance.ill.ever.have.to.see.it" +
            ".vanessa.i.just.wanna.say.im.sorry.i.never.meant.it.to.turn.out.like.this.i.know" +
            ".me.neither.tournament.of.roses.roses.cant.do.sports.wait.a.minute.roses.roses.r" +
            "oses.vanessa.roses.barry.roses.are.flowers.yes.they.are.flowers.bees.pollen.i.kn" +
            "ow.thats.why.this.is.the.last.parade.maybe.not.oould.you.ask.him.to.slow.down.oo" +
            "uld.you.slow.down.barry.ok.i.made.a.huge.mistake.this.is.a.total.disaster.all.my" +
            ".fault.yes.it.kind.of.is.ive.ruined.the.planet.i.wanted.to.help.you.with.the.flo" +
            "wer.shop.ive.made.it.worse.actually.its.completely.closed.down.i.thought.maybe.y" +
            "ou.were.remodeling.but.i.have.another.idea.and.its.greater.than.my.previous.idea" +
            "s.combined.i.dont.want.to.hear.it.all.right.they.have.the.roses.the.roses.have.t" +
            "he.pollen.i.know.every.bee.plant.and.flower.bud.in.this.park.all.we.gotta.do.is." +
            "get.what.theyve.got.back.here.with.what.weve.got.bees.park.pollen.flowers.repoll" +
            "ination.across.the.nation.tournament.of.roses.pasadena.oalifornia.theyve.got.not" +
            "hing.but.flowers.floats.and.cotton.candy.security.will.be.tight.i.have.an.idea.v" +
            "anessa.bloome.ftd.official.floral.business.its.real.sorry.maam.nice.brooch.thank" +
            ".you.it.was.a.gift.once.inside.we.just.pick.the.right.float.how.about.the.prince" +
            "ss.and.the.pea.i.could.be.the.princess.and.you.could.be.the.pea.yes.i.got.it.whe" +
            "re.should.i.sit.what.are.you.i.believe.im.the.pea.the.pea.it.goes.under.the.matt" +
            "resses.not.in.this.fairy.tale.sweetheart.im.getting.the.marshal.you.do.that.this" +
            ".whole.parade.is.a.fiasco.lets.see.what.this.babyll.do.hey.what.are.you.doing.th" +
            "en.all.we.do.is.blend.in.with.traffic.without.arousing.suspicion.once.at.the.air" +
            "port.theres.no.stopping.us.stop.security.you.and.your.insect.pack.your.float.yes" +
            ".has.it.been.in.your.possession.the.entire.time.would.you.remove.your.shoes.remo" +
            "ve.your.stinger.its.part.of.me.i.know.just.having.some.fun.enjoy.your.flight.the" +
            "n.if.were.lucky.well.have.just.enough.pollen.to.do.the.job.oan.you.believe.how.l" +
            "ucky.we.are.we.have.just.enough.pollen.to.do.the.job.i.think.this.is.gonna.work." +
            "its.got.to.work.attention.passengers.this.is.oaptain.scott.we.have.a.bit.of.bad." +
            "weather.in.new.york.it.looks.like.well.experience.a.couple.hours.delay.barry.the" +
            "se.are.cut.flowers.with.no.water.theyll.never.make.it.i.gotta.get.up.there.and.t" +
            "alk.to.them.be.careful.oan.i.get.help.with.the.sky.mall.magazine.id.like.to.orde" +
            "r.the.talking.inflatable.nose.and.ear.hair.trimmer.oaptain.im.in.a.real.situatio" +
            "n.whatd.you.say.hal.nothing.bee.dont.freak.out.my.entire.species.what.are.you.do" +
            "ing.wait.a.minute.im.an.attorney.whos.an.attorney.dont.move.oh.barry.good.aftern" +
            "oon.passengers.this.is.your.captain.would.a.miss.vanessa.bloome.in.24b.please.re" +
            "port.to.the.cockpit.and.please.hurry.what.happened.here.there.was.a.dustbuster.a" +
            ".toupee.a.life.raft.exploded.ones.bald.ones.in.a.boat.theyre.both.unconscious.is" +
            ".that.another.bee.joke.no.no.ones.flying.the.plane.this.is.jfk.control.tower.fli" +
            "ght.356.whats.your.status.this.is.vanessa.bloome.im.a.florist.from.new.york.wher" +
            "es.the.pilot.hes.unconscious.and.so.is.the.copilot.not.good.does.anyone.onboard." +
            "have.flight.experience.as.a.matter.of.fact.there.is.whos.that.barry.benson.from." +
            "the.honey.trial.oh.great.vanessa.this.is.nothing.more.than.a.big.metal.bee.its.g" +
            "ot.giant.wings.huge.engines.i.cant.fly.a.plane.why.not.isnt.john.travolta.a.pilo" +
            "t.yes.how.hard.could.it.be.wait.barry.were.headed.into.some.lightning.this.is.bo" +
            "b.bumble.we.have.some.latebreaking.news.from.jfk.airport.where.a.suspenseful.sce" +
            "ne.is.developing.barry.benson.fresh.from.his.legal.victory.thats.barry.is.attemp" +
            "ting.to.land.a.plane.loaded.with.people.flowers.and.an.incapacitated.flight.crew" +
            ".flowers.we.have.a.storm.in.the.area.and.two.individuals.at.the.controls.with.ab" +
            "solutely.no.flight.experience.just.a.minute.theres.a.bee.on.that.plane.im.quite." +
            "familiar.with.mr.benson.and.his.noaccount.compadres.theyve.done.enough.damage.bu" +
            "t.isnt.he.your.only.hope.technically.a.bee.shouldnt.be.able.to.fly.at.all.their." +
            "wings.are.too.small.havent.we.heard.this.a.million.times.\"the.surface.area.of.t" +
            "he.wings.and.body.mass.make.no.sense.\".get.this.on.the.air.got.it.stand.by.were" +
            ".going.live.the.way.we.work.may.be.a.mystery.to.you.making.honey.takes.a.lot.of." +
            "bees.doing.a.lot.of.small.jobs.but.let.me.tell.you.about.a.small.job.if.you.do.i" +
            "t.well.it.makes.a.big.difference.more.than.we.realized.to.us.to.everyone.thats.w" +
            "hy.i.want.to.get.bees.back.to.working.together.thats.the.bee.way.were.not.made.o" +
            "f.jello.we.get.behind.a.fellow.black.and.yellow.hello.left.right.down.hover.hove" +
            "r.forget.hover.this.isnt.so.hard.beepbeep.beepbeep.barry.what.happened.wait.i.th" +
            "ink.we.were.on.autopilot.the.whole.time.that.may.have.been.helping.me.and.now.we" +
            "re.not.so.it.turns.out.i.cannot.fly.a.plane.all.of.you.lets.get.behind.this.fell" +
            "ow.move.it.out.move.out.our.only.chance.is.if.i.do.what.id.do.you.copy.me.with.t" +
            "he.wings.of.the.plane.dont.have.to.yell.im.not.yelling.were.in.a.lot.of.trouble." +
            "its.very.hard.to.concentrate.with.that.panicky.tone.in.your.voice.its.not.a.tone" +
            ".im.panicking.i.cant.do.this.vanessa.pull.yourself.together.you.have.to.snap.out" +
            ".of.it.you.snap.out.of.it.you.snap.out.of.it.you.snap.out.of.it.you.snap.out.of." +
            "it.you.snap.out.of.it.you.snap.out.of.it.you.snap.out.of.it.you.snap.out.of.it.h" +
            "old.it.why.oome.on.its.my.turn.how.is.the.plane.flying.i.dont.know.hello.benson." +
            "got.any.flowers.for.a.happy.occasion.in.there.the.pollen.jocks.they.do.get.behin" +
            "d.a.fellow.black.and.yellow.hello.all.right.lets.drop.this.tin.can.on.the.blackt" +
            "op.where.i.cant.see.anything.oan.you.no.nothing.its.all.cloudy.oome.on.you.got.t" +
            "o.think.bee.barry.thinking.bee.thinking.bee.thinking.bee.thinking.bee.thinking.b" +
            "ee.wait.a.minute.i.think.im.feeling.something.what.i.dont.know.its.strong.pullin" +
            "g.me.like.a.27millionyearold.instinct.bring.the.nose.down.thinking.bee.thinking." +
            "bee.thinking.bee.what.in.the.world.is.on.the.tarmac.get.some.lights.on.that.thin" +
            "king.bee.thinking.bee.thinking.bee.vanessa.aim.for.the.flower.ok.out.the.engines" +
            ".were.going.in.on.bee.power.ready.boys.affirmative.good.good.easy.now.thats.it.l" +
            "and.on.that.flower.ready.full.reverse.spin.it.around.not.that.flower.the.other.o" +
            "ne.which.one.that.flower.im.aiming.at.the.flower.thats.a.fat.guy.in.a.flowered.s" +
            "hirt.i.mean.the.giant.pulsating.flower.made.of.millions.of.bees.pull.forward.nos" +
            "e.down.tail.up.rotate.around.it.this.is.insane.barry.thiss.the.only.way.i.know.h" +
            "ow.to.fly.am.i.kookookachoo.or.is.this.plane.flying.in.an.insectlike.pattern.get" +
            ".your.nose.in.there.dont.be.afraid.smell.it.full.reverse.just.drop.it.be.a.part." +
            "of.it.aim.for.the.center.now.drop.it.in.drop.it.in.woman.oome.on.already.barry.w" +
            "e.did.it.you.taught.me.how.to.fly.yes.no.highfive.right.barry.it.worked.did.you." +
            "see.the.giant.flower.what.giant.flower.where.of.course.i.saw.the.flower.that.was" +
            ".genius.thank.you.but.were.not.done.yet.listen.everyone.this.runway.is.covered.w" +
            "ith.the.last.pollen.from.the.last.flowers.available.anywhere.on.earth.that.means" +
            ".this.is.our.last.chance.were.the.only.ones.who.make.honey.pollinate.flowers.and" +
            ".dress.like.this.if.were.gonna.survive.as.a.species.this.is.our.moment.what.do.y" +
            "ou.say.are.we.going.to.be.bees.orjust.museum.of.natural.history.keychains.were.b" +
            "ees.keychain.then.follow.me.except.keychain.hold.on.barry.here.youve.earned.this" +
            ".yeah.im.a.pollen.jock.and.its.a.perfect.fit.all.i.gotta.do.are.the.sleeves.oh.y" +
            "eah.thats.our.barry.mom.the.bees.are.back.if.anybody.needs.to.make.a.call.nows.t" +
            "he.time.i.got.a.feeling.well.be.working.late.tonight.heres.your.change.have.a.gr" +
            "eat.afternoon.oan.i.help.whos.next.would.you.like.some.honey.with.that.it.is.bee" +
            "approved.dont.forget.these.milk.cream.cheese.its.all.me.and.i.dont.see.a.nickel." +
            "sometimes.i.just.feel.like.a.piece.of.meat.i.had.no.idea.barry.im.sorry.have.you" +
            ".got.a.moment.would.you.excuse.me.my.mosquito.associate.will.help.you.sorry.im.l" +
            "ate.hes.a.lawyer.too.i.was.already.a.bloodsucking.parasite.all.i.needed.was.a.br" +
            "iefcase.have.a.great.afternoon.barry.i.just.got.this.huge.tulip.order.and.i.cant" +
            ".get.them.anywhere.no.problem.vannie.just.leave.it.to.me.youre.a.lifesaver.barry" +
            ".oan.i.help.whos.next.all.right.scramble.jocks.its.time.to.fly.thank.you.barry.t" +
            "hat.bee.is.living.my.life.let.it.go.kenny.when.will.this.nightmare.end.let.it.al" +
            "l.go.beautiful.day.to.fly.sure.is.between.you.and.me.i.was.dying.to.get.out.of.t" +
            "hat.office.you.have.got.to.start.thinking.bee.my.friend.thinking.bee.me.hold.it." +
            "lets.just.stop.for.a.second.hold.it.im.sorry.im.sorry.everyone.oan.we.stop.here." +
            "im.not.making.a.major.life.decision.during.a.production.number.all.right.take.te" +
            "n.everybody.wrap.it.up.guys.i.had.virtually.no.rehearsal.for.that";

    private Meme() {
    }
}
